Implemente los metodos de la clase vista para el terminal
Vane2005/Proyecto3 pull request #7
Opened 2024-05-18 23:31 UTC by Vane2005

2024-05-19 00:34 UTC, juanda19oficial commented on proyecto3/src/vista/VistaJugadaTerminal.java
> +        for(int i=0; i<3; i++){
![WhatsApp Image 2024-05-18 at 7 11 46 PM](https://github.com/Vane2005/Proyecto3/assets/135680324/b4df9f97-f4cf-40c0-996a-39ebe116c0fc)

aquí la validación debería sumarle 1 a i o decir que muestre error si elige un número menor a cero.

2024-05-19 00:35 UTC, juanda19oficial commented on proyecto3/src/vista/VistaJugadaTerminal.java
> +        switch (opcion) {
![WhatsApp Image 2024-05-18 at 7 22 41 PM](https://github.com/Vane2005/Proyecto3/assets/135680324/9484477c-4de0-4c33-a778-8e00277e7b82)

Cambiar los casos por 0, 1, 2; ya que el usuario está ingresando esos números. realizar el cambio de sumarle 1 al i del print que muestra las opciones.

2024-05-19 00:37 UTC, juanda19oficial commented on proyecto3/src/vista/VistaJugadaTerminal.java
> +                scanner.next();
![WhatsApp Image 2024-05-18 at 7 27 36 PM](https://github.com/Vane2005/Proyecto3/assets/135680324/e773286d-64b8-4afd-bb3d-50667b7034e4)
En este caso no es necesario limpiar memoria ya que está generando un salto al momento de ingresar las opciones.

2024-05-19 00:39 UTC, juanda19oficial requested changes
![WhatsApp Image 2024-05-18 at 7 29 38 PM](https://github.com/Vane2005/Proyecto3/assets/135680324/affcc1bf-d75d-4d0b-9eb5-ddd0f3424746)

Cuando se ingresa una letra, está generando error una excepción.


Finalmente, sería bueno que el programa no finalice hasta que el usuario ingrese una opción de salir.

2024-05-19 00:54 UTC, juanda19oficial commented on proyecto3/src/vista/VistaJugadaTerminal.java
> +        int opcionAleatoriaMaquina = (randomOpcion.nextInt(4)+1);
en esta línea, debería ser "int opcionAleatoriaMaquina = randomOpcion.nextInt(3);" para poder generar un numero entre 0 y 2 (en el caso de que las opciones vayan de 0 a 2). De no ser así, al momento de comparar los casos, no hay una opción por defecto que se realice cuando se genera un numero fuera del rango. 
En el caso de que se sume 1 a i, las opciones serían de 1 a 3 y ps también tocaría sumar 1 al random que genera el número aleatorio.

2024-05-20 14:47 UTC, Vane2005 commented on proyecto3/src/vista/VistaJugadaTerminal.java
> +        for(int i=0; i<3; i++){
Ya realicé todos los cambios solicitados

2024-05-23 16:41 UTC, merged